# Generated by Django 3.2 on 2022-05-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20220504_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AlterField(
            model_name='choice',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
